language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37-django1.11-drf3.8
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37-django3.0-drf3.11
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37-django2.1-drf3.11
  fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
