language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37-django{2.2,3.1,3.2}-drf{3.11,3.12}
    - python: 3.9
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py39-django{2.2,3.1,3.2}-drf{3.11,3.12}
  fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
